<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gmail</name>
   <tag></tag>
   <elementGuidId>4b38ecca-82c7-4ead-878a-f13a3d0012ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfc2f727-de33-48f2-9829-c840ab5cf25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_ua gb_3d gb_6a gb_Rc</value>
      <webElementGuid>8804d9eb-4440-4d9a-806f-1b09806ace37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gb</value>
      <webElementGuid>4b786844-8fe1-4f14-b291-43a6df199f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gmailค้นรูปลงชื่อเข้าสู่ระบบ</value>
      <webElementGuid>78bab86d-1912-4cf7-b04e-4167c541d418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)</value>
      <webElementGuid>c895ddf5-939c-4b82-9f1b-9cce801e3b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gb']</value>
      <webElementGuid>16377b96-0d92-46c7-ad2b-956af3f61984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>82a65e9a-cf2b-4d14-a9f7-9538f24a80f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gb' and (text() = 'Gmailค้นรูปลงชื่อเข้าสู่ระบบ' or . = 'Gmailค้นรูปลงชื่อเข้าสู่ระบบ')]</value>
      <webElementGuid>4701a6a7-2311-4346-94e0-889b21ba0f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
